## Data Import

In [13]:
import pandas as pd     # Pandas is a library for data manipulation and analysis, we use hear to read our data in CSV format
import numpy as np      # Numpy is a library for scientific computing, we use it to perform mathematical operations on our data

# Read in our data
Clustering_df = pd.read_csv('Clustering_Data.csv')        # Read in our data from the CSV file
Clustering_df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1
1,0,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1
2,1,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1
3,1,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5
4,1,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6

In [14]:
# We can do some basic analysis on our data,however for this task the key thing to take note of would be hte number of rows and columns in our data
print(Clustering_df.shape )       
Clustering_df                    # Returns the number of rows and columns in our data

(1500, 17)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.000000,1.620000,64.000000,1,0,2.000000,3.000000,2,0,2.000000,0,0.000000,1.000000,3,3,1
1,0,21.000000,1.520000,56.000000,1,0,3.000000,3.000000,2,1,3.000000,1,3.000000,0.000000,2,3,1
2,1,23.000000,1.800000,77.000000,1,0,2.000000,3.000000,2,0,2.000000,0,2.000000,1.000000,1,3,1
3,1,27.000000,1.800000,87.000000,0,0,3.000000,3.000000,2,0,2.000000,0,2.000000,0.000000,1,4,5
4,1,22.000000,1.780000,89.800000,0,0,2.000000,1.000000,2,0,2.000000,0,0.000000,0.000000,2,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1,29.409825,1.801224,108.156190,1,1,2.385502,2.883984,2,0,2.140544,0,1.144876,1.767468,2,0,2
1496,1,28.421533,1.829239,107.108190,1,1,2.465575,2.935381,2,0,2.480555,0,1.001830,1.670313,2,0,2
1497,0,18.000000,1.692913,89.938890,1,1,2.818502,3.000000,2,0,1.991251,0,1.492967,0.000000,3,3,2
1498,0,18.000000,1.668555,85.607466,1,1,2.081238,3.000000,2,0,1.183630,0,1.171770,0.000000,3,3,2
1499,1,23.246702,1.652971,93.310284,1,1,1.368978,3.000000,2,0,1.953152,0,0.104707,0.221830,3,0,2

In [15]:
# The names of the columns in our data can be optained by looping through the 'columns' attribute of our data and printing each column name
for col in Clustering_df.columns:
    print(col)

Gender
Age
Height
Weight
family_history_with_overweight
FAVC
FCVC
NCP
CAEC
SMOKE
CH2O
SCC
FAF
TUE
CALC
MTRANS
NObeyesdad

## Data Preparation

The dataset you've been given does not need any data preparation. However, you are still required to demostrate some ideas of what you can do to better prepapre the data. In this regard use the cells below to handle Missing Values and Encoding. The Libraries have been import where necessary.

In [16]:
print(Clustering_df.info())                                # Returns the number of rows and columns in our data, the data types of each column and the number of non-null values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          1500 non-null   int64
 1   Age                             1500 non-null   float64
 2   Height                          1500 non-null   float64
 3   Weight                          1500 non-null   float64
 4   family_history_with_overweight  1500 non-null   int64
 5   FAVC                            1500 non-null   int64
 6   FCVC                            1500 non-null   float64
 7   NCP                             1500 non-null   float64
 8   CAEC                            1500 non-null   int64
 9   SMOKE                           1500 non-null   int64
 10  CH2O                            1500 non-null   float64
 11  SCC                             1500 non-null   int64
 12  FAF                             1500 non-null   float64
 13  TUE                             1500 non-null   float64
 14  CALC                            1500 non-null   int64
 15  MTRANS                          1500 non-null   int64
 16  NObeyesdad                      1500 non-null   int64
dtypes: float64(8), int64(9)
memory usage: 199.3 KB
None

No coloumns were dropped as no null values were found. 1500/1500 values present
Given that all values were numerical, no encoding was done

## Clustering

Use k as either 3, 4 OR 5. (Only pick one of the three)

In [20]:
# Use k - Means Clustering to cluster our data and assign each row to a cluster (assing labels to each row). 
# Be carefull with the arguments you pass to the function, make sure you pass the correct
from sklearn.cluster import KMeans

k = 5
kmean=KMeans(n_clusters=k)
kmean.fit(Clustering_df)
kmean.cluster_centers_

# create a new column in our data and assign the cluster labels to each row: this has been partially done for you

Clustering_df['Clusters']=kmean.labels_
Clustering_df.head(20)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Clusters
0,0,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1,3
1,0,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1,0
2,1,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1,1
3,1,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5,1
4,1,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6,1
5,1,29.0,1.62,53.0,0,1,2.0,3.0,2,0,2.0,0,0.0,0.0,2,0,1,0
6,0,23.0,1.50,55.0,1,1,3.0,3.0,2,0,2.0,0,1.0,0.0,2,2,1,0
7,1,22.0,1.64,53.0,0,0,2.0,3.0,2,0,2.0,0,3.0,0.0,2,3,1,0
8,1,24.0,1.78,64.0,1,1,3.0,3.0,2,0,2.0,0,1.0,1.0,1,3,1,3
9,1,22.0,1.72,68.0,1,1,2.0,3.0,2,0,2.0,0,1.0,1.0,3,3,1,3
10,1,26.0,1.85,105.0,1,1,3.0,3.0,1,0,3.0,0,2.0,2.0,2,3,2,2
11,0,21.0,1.72,80.0,1,1,2.0,3.0,1,0,2.0,1,2.0,1.0,2,3,6,1
12,1,22.0,1.65,56.0,0,0,3.0,3.0,2,0,3.0,0,2.0,0.0,2,3,1,0
13,1,41.0,1.80,99.0,0,1,2.0,3.0,2,0,2.0,0,2.0,1.0,1,0,2,2
14,1,23.0,1.77,60.0,1,1,3.0,1.0,2,0,1.0,0,1.0,1.0,2,3,1,3
15,0,22.0,1.70,66.0,1,0,3.0,3.0,0,0,2.0,1,2.0,1.0,2,3,1,3
16,1,27.0,1.93,102.0,1,1,2.0,1.0,2,0,1.0,0,1.0,0.0,2,3,6,2
17,0,29.0,1.53,78.0,0,1,2.0,1.0,2,0,2.0,0,0.0,0.0,3,0,2,1
18,0,30.0,1.71,82.0,1,1,3.0,4.0,1,1,1.0,0,0.0,0.0,3,0,6,4
19,0,23.0,1.65,70.0,1,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,5,3

In [34]:
# train a kNN model to predict the cluster of each row in our test data
# Be careful with the arguments you pass to the function, make sure you pass the correct
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Create an instance of the KNeighborsClassifier class. Set the number of neighbors to 3
kncc = KNeighborsClassifier(n_neighbors=3)

# Specify the columns to use for training i.e. Features (X) and the target column (y). Remeber the tagret is the cluster column from the clustering step

# Splitting the data into train and test models 
# splits 70% of the data for trainning and 30% for testing
train, test = train_test_split(Clustering_df,test_size = 0.3)

X = train.drop('Clusters',axis= 1)
y = train['Clusters']

# Train / fit Features and Taregts to the KNeighborsClassifier model
kncc.fit(X,y)
predictions = kncc.predict(test.drop('Clusters',axis = 1))

print(accuracy_score((test['Clusters']),predictions))

0.9844444444444445

## Classifcation

In [85]:
# Read in our Classification_data from the CSV file
Classification_df = pd.read_csv('Classification_Data.csv')

# Assing each row in our test data to a cluster using the kNN model. Basically we are using our kNN model to predict the cluster of each row in our test data
Classification_df.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,24.481032,1.661277,90.744965,1,1,1.712848,3.000000,2,0,1.162153,0,0.458981,0.885532,3,0,2
1,1,29.000000,1.641784,89.424947,1,1,1.330700,3.000000,2,0,1.880967,0,0.322013,0.000000,2,0,2
2,1,27.968765,1.673767,89.995034,1,1,1.961069,3.000000,2,0,2.652327,0,0.569310,0.319008,2,0,2
3,0,18.024744,1.617192,83.121811,1,1,2.976509,3.000000,2,0,1.022705,0,1.025690,0.313016,3,3,2
4,0,18.106820,1.602129,82.412665,1,1,2.319648,3.000000,2,0,1.107164,0,0.692123,0.304020,3,3,2
5,1,21.379676,1.701413,96.710735,1,1,2.000000,2.961192,2,0,2.623344,0,0.981686,1.355370,3,3,2
6,1,21.353237,1.709731,95.032177,1,1,2.000000,2.973476,2,0,2.000000,0,0.000000,1.331527,3,3,2
7,1,20.338815,1.698829,98.572753,1,1,2.000000,2.392811,2,0,2.000000,0,0.000000,1.809310,3,3,2
8,1,20.720639,1.705304,99.873716,1,1,2.000000,1.293342,2,0,2.000000,0,0.000000,1.917679,3,3,2
9,0,19.045357,1.612910,82.193405,1,1,1.261288,2.930044,2,0,1.166655,0,0.133398,0.951740,3,3,2

In [86]:
Classification_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 611 entries, 0 to 610
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          611 non-null    int64
 1   Age                             611 non-null    float64
 2   Height                          611 non-null    float64
 3   Weight                          611 non-null    float64
 4   family_history_with_overweight  611 non-null    int64
 5   FAVC                            611 non-null    int64
 6   FCVC                            611 non-null    float64
 7   NCP                             611 non-null    float64
 8   CAEC                            611 non-null    int64
 9   SMOKE                           611 non-null    int64
 10  CH2O                            611 non-null    float64
 11  SCC                             611 non-null    int64
 12  FAF                             611 non-null    float64
 13  TUE                             611 non-null    float64
 14  CALC                            611 non-null    int64
 15  MTRANS                          611 non-null    int64
 16  NObeyesdad                      611 non-null    int64
dtypes: float64(8), int64(9)
memory usage: 81.3 KB

In [70]:
# Classification_df['Clusters']=kncc.predict(Classification_df)

In [87]:
Classification_df.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,24.481032,1.661277,90.744965,1,1,1.712848,3.000000,2,0,1.162153,0,0.458981,0.885532,3,0,2
1,1,29.000000,1.641784,89.424947,1,1,1.330700,3.000000,2,0,1.880967,0,0.322013,0.000000,2,0,2
2,1,27.968765,1.673767,89.995034,1,1,1.961069,3.000000,2,0,2.652327,0,0.569310,0.319008,2,0,2
3,0,18.024744,1.617192,83.121811,1,1,2.976509,3.000000,2,0,1.022705,0,1.025690,0.313016,3,3,2
4,0,18.106820,1.602129,82.412665,1,1,2.319648,3.000000,2,0,1.107164,0,0.692123,0.304020,3,3,2
5,1,21.379676,1.701413,96.710735,1,1,2.000000,2.961192,2,0,2.623344,0,0.981686,1.355370,3,3,2
6,1,21.353237,1.709731,95.032177,1,1,2.000000,2.973476,2,0,2.000000,0,0.000000,1.331527,3,3,2
7,1,20.338815,1.698829,98.572753,1,1,2.000000,2.392811,2,0,2.000000,0,0.000000,1.809310,3,3,2
8,1,20.720639,1.705304,99.873716,1,1,2.000000,1.293342,2,0,2.000000,0,0.000000,1.917679,3,3,2
9,0,19.045357,1.612910,82.193405,1,1,1.261288,2.930044,2,0,1.166655,0,0.133398,0.951740,3,3,2

In [88]:
# A second model with k = 7 

kncc2 = KNeighborsClassifier(n_neighbors=7,weights='distance')
train2, test2= train_test_split(Clustering_df,test_size=0.3)

X = train.drop('Clusters', axis=1)
y = train['Clusters']

kncc2.fit(X,y)
preds=kncc2.predict(test2.drop('Clusters',axis=1))
print(accuracy_score((test2['Clusters']),preds))

0.9955555555555555

In [89]:
Classification_df["Clusters"]=kncc2.predict(Classification_df)

In [90]:
Classification_df.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Clusters
0,1,24.481032,1.661277,90.744965,1,1,1.712848,3.000000,2,0,1.162153,0,0.458981,0.885532,3,0,2,1
1,1,29.000000,1.641784,89.424947,1,1,1.330700,3.000000,2,0,1.880967,0,0.322013,0.000000,2,0,2,1
2,1,27.968765,1.673767,89.995034,1,1,1.961069,3.000000,2,0,2.652327,0,0.569310,0.319008,2,0,2,1
3,0,18.024744,1.617192,83.121811,1,1,2.976509,3.000000,2,0,1.022705,0,1.025690,0.313016,3,3,2,1
4,0,18.106820,1.602129,82.412665,1,1,2.319648,3.000000,2,0,1.107164,0,0.692123,0.304020,3,3,2,1
5,1,21.379676,1.701413,96.710735,1,1,2.000000,2.961192,2,0,2.623344,0,0.981686,1.355370,3,3,2,2
6,1,21.353237,1.709731,95.032177,1,1,2.000000,2.973476,2,0,2.000000,0,0.000000,1.331527,3,3,2,2
7,1,20.338815,1.698829,98.572753,1,1,2.000000,2.392811,2,0,2.000000,0,0.000000,1.809310,3,3,2,2
8,1,20.720639,1.705304,99.873716,1,1,2.000000,1.293342,2,0,2.000000,0,0.000000,1.917679,3,3,2,2
9,0,19.045357,1.612910,82.193405,1,1,1.261288,2.930044,2,0,1.166655,0,0.133398,0.951740,3,3,2,1