In [3]:


import pandas as pd
import numpy as np
from datasets import load_dataset
import warnings
warnings.filterwarnings('ignore')

In [ ]:
dataset = load_dataset("swahili_news")

In [5]:
train_texts = dataset["train"]["text"]
train_labels = dataset["train"]["label"]
test_texts = dataset["test"]["text"]
test_labels = dataset["test"]["label"]

In [6]:
df = pd.DataFrame()
df["text"] = train_texts + test_texts
df["label"] = train_labels + test_labels
df["text"].iloc[np.random.choice(df.index, 100, replace=False)] = np.nan
df = df.sample(np.random.randint(24000, 24500))
df = df.reset_index(drop=True)

In [7]:
df.sample()

                                                    text  label
17416   AZAM FC ambayo ipo Uganda ikiendelea na kambi...      2

In [9]:
print("Your final dataset has have {} rows".format(df.shape[0]) + ". This value is randomised and will keep changing every time you run the code/cell.")
print("You have the following value counts for the label column:")
print(df["label"].value_counts())
print("-------" * 10)
df.head()

Your final dataset has have 24391 rows. This value is randomised and will keep changing every time you run the code/cell.
You have the following value counts for the label column:
1    11103
2     6645
4     2350
3     2042
0     1429
5      822
Name: label, dtype: int64
----------------------------------------------------------------------

                                                text  label
0   BENKI ya TPB imekabidhi gawio la Sh bilioni 1...      1
1  EDINBURGH, SCOTLAND MCHEZAJI wa tenisi, Andy M...      2
2  Anna Potinus – Dar es Saaam Msanii wa muziki\n...      5
3   Mkurugenzi wa Uanachama wa TFF, Eliud Mvela a...      2
4    NA KULWA MZEE\n-DAR ES SALAAM MFANYABIASHARA...      1

Using Swahili Stopwords from https://github.com/stopwords-iso/stopwords-iso

In [ ]:
import stopwordsiso as stopwords

stop = stopwords.stopwords('sw')